from js import robot

while robot.is_ok():
     robot.move_forward()
     robot.move_forward()
     robot.move_forward()
     robot.turn_right()
     robot.move_forward()
     robot.move_forward()
     robot.move_forward()
     robot.turn_right()
     robot.move_forward()
     robot.move_forward()
     robot.move_forward()
     robot.turn_right()  
     robot.move_forward()
     robot.turn_right() 
     robot.move_forward()
     robot.move_forward()
     robot.turn_left()
     robot.move_forward()
     robot.turn_left()
     robot.move_forward()
     robot.move_forward()
     robot.turn_right() 
     robot.move_forward()
     robot.turn_right() 
